# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: su gitpod; subin/berth # runs during prebuild
    command: su gitpod; docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web Server
    port: 1984
    onOpen: open-preview
    visibility: public
  - name: Database
    port: 3384
    onOpen: ignore
    visibility: public
