# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start Docker Environment
    before: bin/berth # runs during prebuild
    command: |
      CURRENT_UID=$(id -u):$(id -g) docker-compose up -d
      gp sync-done docker
  - name: Wordpress Core Install
    command: |
      gp sync-await docker
      sleep 3
      CURRENT_UID=$(id -u):$(id -g) GITPOD_URL=$(gp url 1984) docker compose run wordpress-cli core install --url="${GITPOD_UR}L" --title="test" --admin_user="admin" --admin_password="admin" --admin_email="mike.pisula@integrityxd.com"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Web Server
    port: 1984
    onOpen: open-preview
    visibility: public
  - name: Database
    port: 3306
    onOpen: ignore
    visibility: public
