# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: bin/berth # runs during prebuild
    command: echo 'Gitpodding!'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1984
    onOpen: open-preview
