services:
  web:
    container_name: web
    build:
      dockerfile: ./bin/docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./vendor:/var/www/html/vendor:rw
      - ./wordpress:/var/www/html/wordpress:rw
      - ./bin/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    container_name: wordpress
    build:
      dockerfile: ./bin/docker/php/Dockerfile
      target: wordpress
    volumes:
      - ./vendor:/var/www/html/vendor:rw
      - ./wordpress:/var/www/html/wordpress:rw
      - ./bin/docker/php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
  wordpress-cli:
    container_name: wordpress-cli
    build:
      dockerfile: ./bin/docker/php/Dockerfile
      target: wordpress-cli
    volumes:
      - ./vendor:/var/www/html/vendor:rw
      - ./wordpress:/var/www/html/wordpress:rw
      - ./bin/docker/php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
  composer:
    container_name: composer
    image: composer   
    volumes:
      - ./:/app 
  db:
    container_name: db
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports: 
      - "127.0.0.1:3306:3306"
volumes:
  db_data: